### ISSUE TITLE
Possible *bcd issue

### ISSUE THREAD

**Issue by fedex81** [TomHarte/CLK#1011]
Hello,
first of all, thanks for providing the json tests for m68k, always great to find more test cases.
I'm getting a few mismatches on *BCD, even if I ignore the flags, ie:

```
java.lang.AssertionError: 00000100   8303                     sbcd     d3,d1 -- ERROR
Before: M68kState{sr=271e, pc=100, ssp=cbf649dc, usp=1478bb12, opcode=8303, dr=[1647744826, 1845679324, 2078601200, 1933882650, 600718012, 947003136, 1280415642, 12068506], ar=[971934330, 1539682034, 258015894, 703663972, 287933374, 1015576934, 601503382, -873051684]}
Expect: M68kState{sr=2711, pc=102, ssp=cbf649dc, usp=1478bb12, opcode=0, dr=[1647744826, 1845679201, 2078601200, 1933882650, 600718012, 947003136, 1280415642, 12068506], ar=[971934330, 1539682034, 258015894, 703663972, 287933374, 1015576934, 601503382, -873051684]}
Actual: M68kState{sr=2711, pc=102, ssp=cbf649dc, usp=1478bb12, opcode=0, dr=[1647744826, 1845679297, 2078601200, 1933882650, 600718012, 947003136, 1280415642, 12068506], ar=[971934330, 1539682034, 258015894, 703663972, 287933374, 1015576934, 601503382, -873051684]}
```

My [implementation](https://github.com/fedex81/m68k/blob/master/src/m68k/cpu/instructions/SBCD.java) follows what is specified here:
https://github.com/flamewing/68k-bcd-verifier

**Comment by TomHarte** [comment]
I think it's pretty likely the included tests are wrong in that case; I'll check it out. I couldn't find any other test cases whatsoever when I first set out, so I'll definitely consume that BCD verifier post haste.

If you know anything else I could be testing against, especially if it can easily be automated, I'd love to hear about it.

**Comment by fedex81** [comment]
Never looked into it, but this looks very thorough:
https://github.com/tonioni/WinUAE/tree/master/cputest

**Comment by TomHarte** [comment]
I'll need to look into those cputests at some point as I'm still unclear on the proper flags outcome for DIVU and DIVS, but the linked pull request should fix all BCD test cases, pulling them into line with your implementation and that of https://github.com/flamewing/68k-bcd-verifier
