### ISSUE TITLE
CPC6128 – Only 64K of RAM

### ISSUE THREAD

**Issue by noxegon** [TomHarte/CLK#1015]
The CPC6128 appears to only present 64K of RAM. Software that requires 128K does not run. 

This can be tested using The Demo: https://www.pouet.net/prod.php?which=1185

**Comment by TomHarte** [comment]
Ugh, it's worse than that — an uninitialised variable means that whether any CPC has 64kb or 128kb is unpredictable. Fixing momentarily.
