### ISSUE TITLE
Compilation error: off_t was not declared

### ISSUE THREAD

**Issue by koodikone** [TomHarte/CLK#1024]
I get compile errors on FreeBSD 13.0, SDL binding, master branch:

 ... /CLK/Storage/Disk/DiskImage/Formats/Utility/ImplicitSectors.cpp: In function 'std::shared_ptr<Storage::Disk::Track> Storage::Disk::track_for_sectors(const uint8_t*, int, uint8_t, uint8_t, uint8_t, uint8_t, bool)':

... /Storage/Disk/DiskImage/Formats/Utility/ImplicitSectors.cpp:24:2: error: 'off_t' was not declared in this scope
   24 |  off_t byte_size = off_t(128 << size);
      |  ^~~~~
...

It looks like "off_t" is not defined, and if I add "#include <sys/types.h>" to following files, the compilation will be successful:

Storage/Disk/DiskImage/Formats/Utility/ImplicitSectors.cpp
Storage/Disk/Track/PCMTrack.cpp
Storage/Disk/Track/PCMSegment.cpp

**Comment by TomHarte** [comment]
Having had a quick look into it, it seems that `off_t` is non-standard, so I should probably substitute something else. I'll try to get to it this week, as it shouldn't be a big issue. Thanks for letting me know!
