### ISSUE TITLE
Writing to a ProDOS Disk corrupts the disk image

### ISSUE THREAD

**Issue by cybernesto** [TomHarte/CLK#1079]
Booting ProDOS 2.0.3 on an enhanced Apple II and writing:
```
]NEW
]10 PRINT "HELLO"
]SAVE TEST
```
and rebooting causes the disk image to stop working.

**Comment by TomHarte** [comment]
Ugh, almost certainly I've made some sort of error in sector reinterleaving. I'm currently looking into adding support for ProDOS hard disks so I definitely need to get on top of this. Will look at it shortly.
