### ISSUE TITLE
Amiga crashes

### ISSUE THREAD

**Issue by noxegon** [TomHarte/CLK#1084]
In the 2022-07-23 release, File->New, choose Amiga, hit "Choose" => crash.

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 13 Crashed:
0   Clock Signal                  	       0x102ee7656 0x102cc0000 + 2258518
1   libsystem_pthread.dylib       	    0x7ff80c0e14e1 _pthread_start + 125
2   libsystem_pthread.dylib       	    0x7ff80c0dcf6b thread_start + 15

Thread 13 crashed with X86 Thread State (64-bit):
  rax: 0x00000000000e0282  rbx: 0x0000086321f6f371  rcx: 0x0000000000000000  rdx: 0x0000000000002405
  rdi: 0x0000000000000000  rsi: 0x0000000000000001  rbp: 0x0000700003784fb0  rsp: 0x0000700003784f50
   r8: 0x0000000000000001   r9: 0xffffffff00000000  r10: 0x00007fbe9bb3ac18  r11: 0x0000000000000246
  r12: 0x00007fbe9bb3ac40  r13: 0x00006000003c6880  r14: 0x00006000003c68b0  r15: 0x00007fbe9bb3abd0
  rip: 0x0000000102ee7656  rfl: 0x0000000000010216  cr2: 0x0000000000000000

**Comment by TomHarte** [comment]
So I've made a dumb mistake with presentation of the ROM requester — the dialogue that shows up if you want to start a machine for which the ROMs aren't included in the build. The Amiga is one such machine, but you should see the same crash if you try to start a Macintosh (unless you've supplied the ROMs to a previous version of the app, of course). You shouldn't see an issue if you try to start a ZX Spectrum.

Assuming that diagnosis is correct, #1086 should work as a fix. I'll get a new release out.
