### ISSUE TITLE
Where to put ROM files?

### ISSUE THREAD

**Issue by bodhi-baum** [TomHarte/CLK#1110]
I just installed CLK via snap onto Linux. Now I wonder where to put the necessary Roms. If I put them into the current snap-folder they don´t seem to be recognised. Tested this with Oric where I am sure to have possible Roms.

**Comment by TomHarte** [comment]
On that version if you start a machine and haven't yet imported the ROMs then a dialogue should appear asking you to drag and drop, after which the application will automatically store them in the appropriate location based on their contents.

If you want to take charge manually then to achieve that it trusts Qt to provide an appropriate location for its storage, which the documentation suggests will be one of `"~/.local/share/<APPNAME>"`, `"/usr/local/share/<APPNAME>"` or `"/usr/share/<APPNAME>"`.

**Comment by bodhi-baum** [comment]
Ok, thank you for that information.
