### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by hfath** [TomHarte/CLK#1118]
On MacOS X 10.13, the latest CLK (2022-11-25) fails to start with

```
Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/USER/*/Clock Signal.app/Contents/MacOS/Clock Signal
  Reason: image not found
```

Full stack trace here:
[CLK-stacktrace.txt](https://github.com/TomHarte/CLK/files/10679866/CLK-stacktrace.txt)

**Comment by TomHarte** [comment]
This is initially a bit of a mystery to me; I'll figure it out. 10.13 is still listed in the Xcode pull-down for deployment targets, so it's more likely I've done something wrong than that the toolchain is suddenly making the wrong decision re: embedding Swift or not. I'll experiment.
