### ISSUE TITLE
Play button / documentation

### ISSUE THREAD

**Issue by RolandTi** [TomHarte/CLK#1119]
Hello ! 
Thanks you for making an easy app to help peoples to discover old videogames.
But... :)
I tried Atic Atac on ZX, and I'm stuck on the title screen. The manual say, press 'play'. But which input key it is ? 
Space bar made me back to the "128" menu. 
Is there any document for the mapping ?
Thanks in advance :-)

**Comment by TomHarte** [comment]
Is the specific version of Atic Atac that you downloaded available online somewhere? This could be an emulator issue; at a guess the screen you're seeing is asking you to press play on your tape drive (which the emulator intends to do automatically) but then the game itself is crashing, prompting the machine restart.

So it could be that the machine is acting incorrectly, it could be that your particular copy of Atic Atac doesn't work on 128kb machines (in which case the emulator is at fault for selecting one), or technically the image could be faulty. But that's least likely.

**Comment by RolandTi** [comment]
> at a guess the screen you're seeing is asking you to press play on your tape drive (which the emulator intends to do automatically) but then the game itself is crashing, prompting the machine restart.

You're right ! I tried an another rom and it's working. The working one is `Atic Atac (1983)(Ultimate Play The Game).z80` and the buggy one `Atic Atac (1983)(Ultimate).tap` (if you're interested, here is the rom : https://we.tl/t-glBFLHnPNO)

Thanks !
