### ISSUE TITLE
[Electron] Improvement to paging logic

### ISSUE THREAD

**Issue by haerfest** [TomHarte/CLK#1175]
In a [thread on the Stardot forum](https://stardot.org.uk/forums/viewtopic.php?t=27791) it was revealed that Electron OS 1.00 expects  SHEILA &FE05, used to both clear interrupts and page in sideways RAM/ROM, to only page when all interrupt-clearing bits are zero, i.e. &0x. Most expansions that support sideways RAM/ROM, such as the Plus 1, implement logic to that effect.

Clock Signal currently honours every paging request, which in specific circumstances could lead to the OS inadvertently paging in bank #0 when servicing interrupts.

Probably placing the paging logic of [Electron.cpp lines 293-305](https://github.com/TomHarte/CLK/blob/90f0e937e81cd7e020f6ec5a60710bab18b4f160/Machines/Electron/Electron.cpp#L293) in an `else` branch is sufficient.

**Comment by TomHarte** [comment]
Yeah, agreed — that's the correct fix. Thanks for both reporting and resolving the issue!
