### ISSUE TITLE
Auto comment feature

### ISSUE THREAD

**Issue by shraddha761** [TomHarte/CLK#1187]
There should be an auto comment feature while creating issue , assigning and creating pr.
Assign this issue to me

**Comment by ryandesign** [comment]
You're suggesting that a bot should automatically add a comment when an issue or PR is opened? It's up to Thomas, of course, but I don't know why anyone would want that.

I see that you opened a PR for this and then closed it.

I see you've made this same suggestion in many other repositories recently, perhaps as part of participating in Hacktoberfest, and that some of those projects have similarly rejected this proposal.

I encourage you to try to make more meaningful substantive contributions instead.

**Comment by shraddha761** [comment]
@ryandesign I did this only in one repo I am know about workflow and also learn yml recently that's why I thought this as meaningful apologize for any inconveniences

**Comment by ryandesign** [comment]
> I did this only in one repo

Oh? On October 27 and 28, in addition to this issue, you opened:

https://github.com/soot-oss/SootUp/pull/730
https://github.com/lobehub/lobe-chat/pull/375
https://github.com/ccbogel/QualCoder/issues/842
https://github.com/THUDM/AgentTuning/issues/21
https://github.com/lobehub/lobe-chat/issues/374
https://github.com/oceanbase/oceanbase/issues/1627
https://github.com/Clueless-Community/scrape-up/issues/847

**Comment by Killer2OP** [comment]
> > I did this only in one repo
> 
> Oh? On October 27 and 28, in addition to this issue, you opened:
> 
> [soot-oss/SootUp#730](https://github.com/soot-oss/SootUp/pull/730) [lobehub/lobe-chat#375](https://github.com/lobehub/lobe-chat/pull/375) [ccbogel/QualCoder#842](https://github.com/ccbogel/QualCoder/issues/842) [THUDM/AgentTuning#21](https://github.com/THUDM/AgentTuning/issues/21) [lobehub/lobe-chat#374](https://github.com/lobehub/lobe-chat/issues/374) [oceanbase/oceanbase#1627](https://github.com/oceanbase/oceanbase/issues/1627) [Clueless-Community/scrape-up#847](https://github.com/Clueless-Community/scrape-up/issues/847)

It depends on the maintainer , I was suggesting it and it was only acceptapologize for any inconveniencesed in lobechat that,swhy i said only one.
I apologize for any inconveniences.
Thanks.

**Comment by shraddha761** [comment]
> > I did this only in one repo
> 
> Oh? On October 27 and 28, in addition to this issue, you opened:
> 
> [soot-oss/SootUp#730](https://github.com/soot-oss/SootUp/pull/730) [lobehub/lobe-chat#375](https://github.com/lobehub/lobe-chat/pull/375) [ccbogel/QualCoder#842](https://github.com/ccbogel/QualCoder/issues/842) [THUDM/AgentTuning#21](https://github.com/THUDM/AgentTuning/issues/21) [lobehub/lobe-chat#374](https://github.com/lobehub/lobe-chat/issues/374) [oceanbase/oceanbase#1627](https://github.com/oceanbase/oceanbase/issues/1627) [Clueless-Community/scrape-up#847](https://github.com/Clueless-Community/scrape-up/issues/847)

@ryandesign It totally depends on the maintainer.
If the maintainer wants to make a good and understanding repository , They consider the suggestion.
Some maintainers understand some may not. 
Only lobechat understood the idea behind it.
thatswhy i said only one.
Thanks.
