### ISSUE TITLE
libswiftCore.dylib Library not loaded on macOS High Sierra

### ISSUE THREAD

**Issue by ryandesign** [TomHarte/CLK#1191]
As previously reported in #1118 and #1143, Clock Signal does not launch on macOS High Sierra 10.13.6.

Initially the error was:

```
Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /path/to/*/Clock Signal.app/Contents/MacOS/Clock Signal
  Reason: image not found
```

It's looking for libswiftCore.dylib but doesn't know where to find it. In #1164 a fix was committed which added these lines to both debug and release:

https://github.com/TomHarte/CLK/blob/3d5a3513068fa094277357dfa093600d026009c9/OSBindings/Mac/Clock%20Signal.xcodeproj/project.pbxproj#L6589-L6592

The fix landed in release 23.09.10 although it was not mentioned in the release notes. This still fails to launch:

```
Dyld Error Message:
  Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /path/to/*/Clock Signal.app/Contents/MacOS/Clock Signal
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/Swift/libswiftCore.dylib/libswiftCore.dylib: stat() failed with errno=20
```

Now it has an idea of where to look, but `stat` is returning error code 20, meaning "not a directory". True: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib is not a directory; it is wrong to treat it as one. The fix was wrong because `LD_RUNPATH_SEARCH_PATHS` must be the path to directories in which libraries can be found, not the path to the libraries themselves.

I tried this change to fix that:

```diff
--- a/OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj     
+++ b/OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj     
@@ -6653,7 +6653,7 @@
                                INFOPLIST_FILE = "Clock Signal/Info.plist";
                                LD_RUNPATH_SEARCH_PATHS = (
                                        "$(LD_RUNPATH_SEARCH_PATHS_$(IS_MACCATALYST))",
-                                       /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib,
+                                       /System/Library/PrivateFrameworks/Swift,
                                );
                                MACOSX_DEPLOYMENT_TARGET = 10.13;
                                MTL_TREAT_WARNINGS_AS_ERRORS = YES;
@@ -6700,7 +6700,7 @@
                                INFOPLIST_FILE = "Clock Signal/Info.plist";
                                LD_RUNPATH_SEARCH_PATHS = (
                                        "$(LD_RUNPATH_SEARCH_PATHS_$(IS_MACCATALYST))",
-                                       /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib,
+                                       /System/Library/PrivateFrameworks/Swift,
                                );
                                MACOSX_DEPLOYMENT_TARGET = 10.13;
                                MTL_TREAT_WARNINGS_AS_ERRORS = YES;
```

However it still does not launch:

```
Dyld Error Message:
  Symbol not found: _$s15_ObjectiveCTypes01_A11CBridgeablePTl
  Referenced from: /path/to/*/Clock Signal.app/Contents/MacOS/Clock Signal
  Expected in: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib
 in /path/to/*/Clock Signal.app/Contents/MacOS/Clock Signal
```

Now it can find the library in the private frameworks, but evidently High Sierra's private copy of libswiftCore.dylib does not contain a symbol that the one on my Monterey machine (where I built the revised app) does. Probably Clock Signal shouldn't be trying to use a private framework anyway.

It has been years since I played with Swift but back when I did, Xcode would automatically copy the Swift dylibs into the app bundle, and indeed that appears still to be the case now if your deployment target predates the inclusion of Swift libraries in the OS, which it does. I don't know where the official documentation of that is, but I found the Swift System Libraries section of this post by Quinn "The Eskimo!" who always seems to know what he's talking about:

https://developer.apple.com/forums/thread/736728

But even though you already bundle the Swift libraries, you're not using them. That developer forum post, and also inspection of some other apps on my system that have bundled Swift libraries, shows that the runtime path should be `@loader_path/../Frameworks`. (Quinn's post omits `../` because it's talking about iOS not macOS.) Recompiling with that change allows the app to open and work normally on High Sierra for me.

-----

Users wishing to use the binary of release 23.09.10 without recompiling it can copy it to the Desktop and then run these commands in the Terminal:

```
install_name_tool -delete_rpath /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib -add_rpath @loader_path/../Frameworks "$HOME/Desktop/Clock Signal.app/Contents/MacOS/Clock Signal"
codesign -fs - "$HOME/Desktop/Clock Signal.app/Contents/MacOS/Clock Signal"
```

The `install_name_tool` command replaces the invalid runtime path with the correct one. This is of course a modification of the program, and any modification to a program breaks its code signature and makes the OS refuse to run it. The `codesign` command creates a new ad-hoc code signature that allows the app to run again.

**Comment by TomHarte** [comment]
A signed build with #1192 applied is attached for further inspection.
[Clock Signal macOS 2023-10-28.zip](https://github.com/TomHarte/CLK/files/13196602/Clock.Signal.macOS.2023-10-28.zip)

**Comment by ryandesign** [comment]
That build works for me on High Sierra too!
