### ISSUE TITLE
Apple II text should have color fringes in graphics modes

### ISSUE THREAD

**Issue by ryandesign** [TomHarte/CLK#1271]
Run this Applesoft BASIC program in a Clock Signal Apple //e:

```bas
1GR:COLOR=2:FORI=0TO39:HLIN0,39ATI:NEXT:?"HELLO WORLD
```

The actual output is:

![nocolorbursttext](https://github.com/TomHarte/CLK/assets/429209/eff00b61-2408-4512-ab83-d51769ee84d8)

This isn't authentic. A real Apple II outputs the color burst on all scanlines when in a graphics mode, even on the last 32 scanlines which are displayed as text if mixed mode is on. Expected output is:

![colorbursttext](https://github.com/TomHarte/CLK/assets/429209/a445b833-6218-4390-9b82-a7d8ce5af1da)

**Comment by TomHarte** [comment]
Oh, I had previously understood that the bug was that real-life CRTs don't treat presence-of-absence of a colour burst as a digital-domain-esque line-by-line yes or no, instead requiring that it be absent for "a while" before conceding that there's no colour to decode. So I didn't want to change anything on the Apple II side, believing this to be a CRT issue.

If the Apple II continues producing the colour burst even in those four lines then the fix is certainly easy.

**Comment by ryandesign** [comment]
[*Understanding the Apple IIe*, page 8-6](https://archive.org/details/Understanding_the_Apple_IIe/page/n211/mode/1up):

"The COLOR BURST does not occur if the TEXT soft switch is set. When no COLOR BURST is present, the color generation in the television is inhibited, so elimination of the BURST prevents undesirable coloration of screen text. The COLOR BURST is not inhibited during TEXT time in MIXED mode, so the four lines of text at the bottom of the screen in MIXED displays have coloration (green, violet, and white assuming SINGLE-RES display mode)."

[*Understanding the Apple II*, page 8-5](https://archive.org/details/understanding_the_apple_ii/page/n200/mode/1up):

"In the oldest Apple IIs (Revision 0), the COLOR BURST was always present on the VIDEO signal. This resulted in distracting green and violet text characters. A Color Burst Killer was added in Revision 1 to eliminate the COLOR BURST in TEXT MODE. This removed the colors from the text because the television uses the presence of the COLOR BURST to determine whether an incoming signal is a color signal or a monochrome signal. When no COLOR BURST is present, it completely inhibits color generation in the television so the picture is black and white with no color noise. In MIXED mode, the four lines of text at the bottom of the screen are still green and violet because the COLOR BURST is still present."

**Comment by ryandesign** [comment]
I imagine the reason why the Apple II leaves the color burst either always on or always off is because CRTs got confused otherwise.

[*Enhancing your Apple II and IIe Volume 2*](https://www.tinaja.com/ebooks/enhance_vII.pdf), Enhancement 13, The Vaporlock, page 222:

"As a final gotcha, remember that any text mode that exits during the horizontal blanking time will try to kill the color. If too many horizontal lines do not have color reference bursts, your color monitor or tv might get its colors mixed up or dropped entirely. Fortunately, it takes lots of missed bursts to foul up the works on most sets, so just keep as many lines out of the text mode during horizontal blanking as you can."
