### ISSUE TITLE
zip file attached to 2024-01-22 release misnamed?

### ISSUE THREAD

**Issue by ryandesign** [TomHarte/CLK#1319]
The file attached to release 2024-01-22 is named Clock.Signal.macOS.2024-01-21.zip but the app inside it has version number 24.01.22 so I think just the zip file is misnamed and it should be renamed to Clock.Signal.macOS.2024-01-22.zip.

**Comment by TomHarte** [comment]
I feel fairly foolish now; I've used `date -u` in the script that sets the version number despite living on the East Coast of the USA and therefore failed to notice that it was the 22nd over in UTC world while it was still the 21st where I was sitting.

Will rename ZIP.
