### ISSUE TITLE
FR: VSync hack for Oric

### ISSUE THREAD

**Issue by polluks** [TomHarte/CLK#1398]
See https://forum.defence-force.org/viewtopic.php?p=15153

**Comment by TomHarte** [comment]
Naturally I am strongly in favour of [url=https://forum.defence-force.org/viewtopic.php?p=15173#p15173]software vsync[/url] but I'll see what I can do. It looks like I can predicate whether vsync or tape input is active from the motor control so I should even be able to get something within the usual bounds of this emulator — i.e. anything that increases compatibility with no user input is definitely within scope.
