### ISSUE TITLE
Spectrum: Game doesn't load

### ISSUE THREAD

**Issue by polluks** [TomHarte/CLK#1406]
See https://mojontwins.itch.io/orbol-voon/purchase
```
mojon-twins--orvol-voon--EN-v1.1.tap: Spectrum TAP format
-r--r--r-- BASIC         222 PERILS
-r--r--r-- Headerless     72 (Headerless block)
-r--r--r-- Headerless  21622 (Headerless block)
-r--r--r-- Headerless   8104 (Headerless block)

**Comment by TomHarte** [comment]
Kneejerk observation: this issue persists and is visually identical regardless of whether fast loading is enabled, and across all models with the slight variation that the 48kb resets itself whether the various 128kb models don't.

**Comment by polluks** [comment]
Looks like nonsense

; tap2bas - Sinclair ZX Spectrum Basic source code generator
; Copyright (c) 2017 Petr Sladek (slady)
;
; generated from a tape file named: "PERILS"
;
12679 OVER  USR 7]7> COPY  INVERSE !X COPY `11;`00;`00; STEP V`05; NEXT !X COPY `11;`00;@ STEP d]7> COPY  INVERSE !`12; COPY `11;F`00; STEP V`05; NEXT  STEP W]!`12; COPY `11;`00;@ STEP d]7> COPY  INVERSE ! DATA  SCREEN$ `11;tT STEP V`05; NEXT  CODE  OPEN #  RETURN ! DATA  SCREEN$ `11;`88;^ STEP d]`01; CLEAR `7f; CODE  GO SUB y:`01;`00;g>`10; GO SUB y:`01;`00; SGN (`1c;>`11;`01; CLEAR `7f; GO SUB y7> COPY  INVERSE !`00; USR `11; INKEY$ `1f; STEP V`05; NEXT >`10;`01; CLEAR `7f; GO SUB y NOT `88;^`01; COPY `02;!`00;X`11;`01;Xu GO SUB  VAL  <> >`80; GO SUB `a0; STEP `a3;]0 RANDOMIZE  MERGE `01;`00;`00;P`14; STEP `a3;]0 IF  CLOSE # `a3;] THEN `11; THEN `10;8`1f;`15;  POKE `03;^# THEN 30`0c;`16;`10; STEP `a3;] THEN `12;0 RANDOMIZE `14; THEN : THEN `1b; READ  RESTORE  GO SUB R MOVE  GO SUB  VAL  LLIST 0 OR `87; USR `7e;#`17; <>

**Comment by TomHarte** [comment]
Further to this, I got exactly the same behaviour in FUSE as I get in Clock Signal.

FUSE:
<img width="796" alt="Screenshot 2024-10-09 at 12 57 50" src="https://github.com/user-attachments/assets/eda4c157-bee6-434d-961c-bc196f129740">

Clock Signal:
<img width="712" alt="Screenshot 2024-10-09 at 12 59 11" src="https://github.com/user-attachments/assets/6be7d516-8a4b-4ba0-b2b8-29861922a9ab">

**Comment by hippietrail** [comment]
I just tested it in [Retro Virtual Machine](https://www.retrovirtualmachine.org/) (my favourite Speccy emulator) and it's the same. 48K resets after showing this, 128K maintains this display.

**Comment by polluks** [comment]
I see, at least version 1.0 works.
