### ISSUE TITLE
Updated icon design proposal

### ISSUE THREAD

**Issue by maxtron95** [TomHarte/CLK#1415]
I decided to design a new icon for Clock Signal to fit in with other icons newer macOS versions. I also included a non-rounded variant for non-Mac systems like Linux or Windows. 

For the icon, I tried to replicate a CRT monitor and incorporated a pixel clock design in the icon. 

I also updated icons for the filetypes as well. I created an extra variant for the cartridge icon with a label in case.

![clk-new-design](https://github.com/user-attachments/assets/44a7aee7-d442-4e92-adf3-ffd05d8f637e)
[CLK.zip](https://github.com/user-attachments/files/17775555/CLK.zip)

**Comment by TomHarte** [comment]
These look fantastic, thanks! I have been on a slight sojourn into another project but I'm going to get right on top of this.
