### ISSUE TITLE
macOS - "QuickLook" icon preview looks like the default Apple application icon.

### ISSUE THREAD

**Issue by nekoniaow** [TomHarte/CLK#376]
This is certainly not a big issue but on Sierra (10.12.6), after obtaining the latest release from GitHub and extracting it from the archive, the quicklook icon which appears in the Finder looks like the generic Apple application image:

<img width="373" alt="clock signal" src="https://user-images.githubusercontent.com/7558773/37808586-856ab9c2-2e21-11e8-96da-a34561572de9.png">

The app's icon itself as shown next to the file name seems normal (a dark/grey CRT monitor).

**Comment by TomHarte** [comment]
I'm actually unable to reproduce this, so pull request #384 is a guess.

**Comment by TomHarte** [comment]
https://github.com/TomHarte/CLK/releases/tag/2018-03-23 contains the attempted fix; if you get a chance to test it then let me know!

**Comment by nekoniaow** [comment]
I confirm this is fixed when building from sources as well as when using the released version.
Thanks!

**Comment by nekoniaow** [comment]
Just realized I could close this bug, is this expected/normal?
