### ISSUE TITLE
macOS - GateKeeper : App is from an unidentified developer.

### ISSUE THREAD

**Issue by nekoniaow** [TomHarte/CLK#377]
When attempting to open the latest release on macOS Sierra (10.12.6) (*),
GateKeeper indicates that the application is from an unidentified developer and thus cannot be opened.

This can of course be worked around manually but it is probably a good idea to not teach users to ignore GateKeeper warnings and to properly register the app to Apple instead.
The required fee is not too high (90$ if I recall correctly).

As a developer and end user, I would feel much safer knowing that the app is running under the protection of GateKeeper.

Thanks!

<img width="448" alt="screen shot 2018-03-22 at 22 41 50" src="https://user-images.githubusercontent.com/7558773/37808719-47b8f4f8-2e22-11e8-8894-d4d40fb21db2.png">

(*) https://github.com/TomHarte/CLK/releases/download/2018-03-22/Clock.Signal.macOS.2018-03-22.zip

**Comment by TomHarte** [comment]
Agreed that for an emulator that is supposed to be about user experience, this is a substantial blemish. I think Apple's fee is per year but, either way, it's probably worth it.

**Comment by nekoniaow** [comment]
Thanks!
I would definitely be willing to contribute to that fee if possible.
This is actually one of the reasons I do not mind to pay for apps, nothing is ever free. ;)

**Comment by TomHarte** [comment]
The app is notarised as of the 2020-11-13 release; that means that as of macOS Big Sur the dialogue upon a first launch is similar to:
<img width="372" alt="Screenshot 2020-11-13 at 12 44 45" src="https://user-images.githubusercontent.com/1162152/99103758-11e9bc00-25ae-11eb-8ca5-131ec051bba3.png">
i.e. it contains a direct 'Open' button and a confirmation that nothing malicious is included. This is Apple's current preferred way to distribute non-App Store apps, so this ticket is finally done.
