### ISSUE TITLE
macOS Sierra - CLK crashes when attempting to create a new tab

### ISSUE THREAD

**Issue by nekoniaow** [TomHarte/CLK#388]
With release https://github.com/TomHarte/CLK/releases/download/2018-03-23/Clock.Signal.macOS.2018-03-23.zip,

(With CLK automatically loading the kindness.d64 disk image mentioned in #378 )
Start CLK
Notice the VIC20 display window opens with kindness.d64 being loaded
Access the menu entry "View -> Show Tab Bar" to have the tab bar showing.
Click the "+" button of the tab bar.
Notice that CLK crashes.

**Comment by TomHarte** [comment]
This was exactly the same issue as #387, just reaching the same code by a different route. It's therefore fixed by #400
