### ISSUE TITLE
Typing Command-V after copying some text in the Oric BASIC results in string of "V" characters.

### ISSUE THREAD

**Issue by nekoniaow** [TomHarte/CLK#435]
Using the latest version (https://github.com/TomHarte/CLK/releases/tag/2018-04-13).
Under macOS (Sierra 10.12.6).
Using a new instance of the Oric/Atmos (no MicroDrive).
Copy (using Command-C) the BASIC program listed in this Defense Force forum thread : http://forum.defence-force.org/viewtopic.php?p=5611#p5611.
Then, selecting the CLK Oric window so it has focus.
Type Command-V to paste the copied program.

Notice that this results in a series of "V" characters (and a few others) typed sequentially in the BASIC window.

Note that, if the Oric window loses focus, the sequence stops and does not resume upon giving it focus again. 

I am not sure if Copy-Pasting of text is actually supported by the emulator (as a naive user, I would expect it to, otherwise I would not have tried this and discovered the issue ;) ) but it seems reasonable to think that the current behavior is not as designed. ;)

Here is the exact text copied from the forum post:

```
1 '***********************
2 ' MICROSOFT! Easter Egg
3 '***********************
4 B=#E435 : E=B+9
5 FOR I=E TO B STEP -1
6 J=PEEK(I) : J=J-INT(J/64)*64
7 IF I>B THEN A$=A$+CHR$(J+64) ELSE A$=A$+CHR$(J)
8 NEXT I
9 PRINT A$
```

This said, I would wager that any copied text causes this result.

On a VIC-20 instance, copying that same text generates a single "V" character but seems to confuse further the input routine:
- Typing the "A" key does not produce any result
- Typing the "Q" key produce the "QV" sequence of characters, "E" gives "EV", and so on...
As for the Oric instance, losing focus and restoring it restores normal behavior.

**Comment by TomHarte** [comment]
Pasting was supported but accidentally broken; I've been working on it this morning. The repeating V is now gone but a further Oric issue reveals itself: on that machine it's implemented as a simple timed operation: press a key, wait, press another key. But the pause between the Oric being able to accept one key and being able to accept the next is a lot longer when you press return at the end of a line of BASIC. So the next line number is missed.

So I need to have a closer look at that. The Oric and one or two other machines (though definitely not all) are either spotting when the key-test routine in ROM is hit or when the keyboard is actually read. I probably need to move the Oric to doing that.

**Comment by TomHarte** [comment]
![oric paste](https://user-images.githubusercontent.com/1162152/39970361-f11e4f8a-56b7-11e8-9e09-735e550c063c.gif)
Fixed as written, as demonstrated in the attached GIF; I need to look into why command+[keys that aren't meant to do anything] causes repeats though.

**Comment by nekoniaow** [comment]
Great picture. ;)
Thank you for the super quick fix.

Being able to paste into the guest machine is immensely practical.
