### ISSUE TITLE
Apple II: Wrong colors when running under MacOS El Capitan (10.11.6)

### ISSUE THREAD

**Issue by cybernesto** [TomHarte/CLK#457]
On the left OpenEmulator, on the right CLK. I don't expect these to match, but there is definitely something wrong in the color emulation of CLK in my configuration. Let me know if I can provide any additional information.
![bildschirmfoto 2018-05-28 um 21 03 00](https://user-images.githubusercontent.com/886427/40626733-b76832d8-62ba-11e8-97a6-464dbd920697.png)

**Comment by TomHarte** [comment]
Oh, gosh, that's miles off. I thought we were just talking about coarse artefacts. I'm going to look at this immediately.

**Comment by TomHarte** [comment]
There are two issues at play here I think:
* being too optimistic about GPU interpolation precision; and
* almost certainly, having flipped my two mapping tables the wrong way around.

Re: the first, I'm attempting to unpack the raw Apple II bytes on the GPU by keeping track of sub-sample position. As attached, that's fine on my machine. I guess it isn't fine in general. I'll probably have to unpack on the CPU.

Re: the second, I think my colour burst is 180 degrees out of phase, and that error has been masked by my having reversed two mapping tables that I use on the CPU side to make every output mode look like double-high resolution mode.

Hence the attached, from my machine, which shows no peculiar banding (that's the GPU precision; I'm being lucky) but still has purple and green transposed (that'll be the phase).

So at least two things to fix.
<img width="712" alt="screen shot 2018-05-28 at 18 29 46" src="https://user-images.githubusercontent.com/1162152/40631193-3b178bb4-62a8-11e8-887d-ff09aa30caa6.png">

**Comment by TomHarte** [comment]
The specific colours is actually a mistake in my handling of PAL and NTSC; the phase of the quadrature signal flips between each line in PAL but it remains constant in NTSC. I've been using the flipped one. It'll take some tidying up but the fix will be coming soon. A screenshot is attached of the rubber-band fix and I'm working on the real one.

No fix to the precision issue yet, but I'm confident that isn't too hard.
<img width="1104" alt="screen shot 2018-05-30 at 22 09 37" src="https://user-images.githubusercontent.com/1162152/40757666-982d6a5c-6457-11e8-9e0c-96f2964d1d46.png">

**Comment by cybernesto** [comment]
Excellent! Thanks for the update.

**Comment by TomHarte** [comment]
This probably isn't the best solution, but give the attached a go if you have a chance — it attempts to keep byte unpacking on the GPU, I'm just not completely persuaded by the approach. It may well be no less problematic.
[Clock Signal.zip](https://github.com/TomHarte/CLK/files/2060818/Clock.Signal.zip)

**Comment by cybernesto** [comment]
Yes! That looks way better.

![bildschirmfoto 2018-06-01 um 11 10 46](https://user-images.githubusercontent.com/886427/40832793-7c9d5500-658c-11e8-8207-80e6c1989105.png)
