### ISSUE TITLE
CLI Flag to locate the ROM images

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#462]
I compile and run CLK using my own user and it is inconvenient to copy the ROM files to a system wide location.

Could it be possible to make that path configurable with a CLI flag?

Thanks!

**Comment by TomHarte** [comment]
This should now work with `--rompath=path`.

**Comment by reidrac** [comment]
Thanks, I don't know how I missed that!

-h doesn't mention is, is thus documented somewhere?
