### ISSUE TITLE
Alt+Enter toggles between fullscreen and windowed mode

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#463]
This is running Linux.

Alt+Enter toggles between fullscreen and windowed mode very fast, perhaps CLK could check that the keys have been released before toggling again.

Currently is bit fiddly to get fullscreen to work.

**Comment by TomHarte** [comment]
Resolved exactly as suggested; best guess is that the KEYDOWN event was being reposted due to some sort of flush of keyboard state so I've switched it to acting upon KEYUP.

**Comment by reidrac** [comment]
Thanks!
