### ISSUE TITLE
Glitch on fullscreen

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#473]
I can see sometimes a glich on fullscreen mode, on the right border of the CRT. Like a vertical line with reminders of blue from the basic screen. I can't seem to be able to take a screenshot, so there you have photo.

![img_20180615_072959531_ll](https://user-images.githubusercontent.com/120189/41453623-5f751da4-706e-11e8-9102-1875f7dd753b.jpg)

It is nothing important, but I thought I would let you know.

**Comment by TomHarte** [comment]
Oh, no, that makes sense. I think a prior sweep of the virtual electron gun has painted further than subsequent sweeps. Might even have been while sync was being established on a new mode. Meanwhile I've erroneously assumed complete overdraw, and the errors would be cropped in windowed mode.

I guess I can either be more careful in painting or crop something negligible like 2% (or whatever the numbers suggest the scan might not reach according to the maximum variation in recognised sync times, which are themselves filtered) even when the size of the display doesn't require it.

So some thinking first, I think.

**Comment by reidrac** [comment]
Also; I've found that the screen is not specially centered.

![screenshot_2018-06-20_20-28-05](https://user-images.githubusercontent.com/120189/41680159-83805aac-74c8-11e8-9607-771067f389c2.png)

**Comment by TomHarte** [comment]
I think that's just because I'm not holding blank after sync; when the CRTC thinks it is time to end sync I instantly jump back to border. So on the left you're seeing extra border that you shouldn't.

(Aside: this is also why I don't yet offer composite video for the CPC — I've not figured out exactly what logic adds the colour burst)

I will endeavour to tackle both issues.

**Comment by TomHarte** [comment]
Re: the second thing, I've tried implementing what I think is the right logic — holding blank until the end of the CRTC's hsync period, subject to inclusion of a colour burst if outputting composite — but now it looks a little thin on the left. It's very curious.

Anyway, attached are screenshots of (i) BASIC; (ii) a tape loading; and (iii) the Renegade title screen, showing that composite output now works. And that I can reproduce the noise-on-the-edge issue.

<img width="1440" alt="basic" src="https://user-images.githubusercontent.com/1162152/41695235-37187014-74dc-11e8-9e77-f805ed2ebcf8.png">
<img width="1440" alt="loading" src="https://user-images.githubusercontent.com/1162152/41695233-36f8b5e4-74dc-11e8-92f6-d102428e6c34.png">
<img width="1440" alt="renegade composite" src="https://user-images.githubusercontent.com/1162152/41695234-37062c9c-74dc-11e8-89e9-8bd0b32978c1.png">

**Comment by reidrac** [comment]
It has improved, but still not perfect. See on window mode.

![screenshot_2018-06-22_21-38-34](https://user-images.githubusercontent.com/120189/41798219-c134494c-7664-11e8-84c6-5a1d1a78cfc8.png)

**Comment by TomHarte** [comment]
Agreed, but I decided that was probably either an issue with the emulated CRTC holding hsync for too long, or I've some sort of memory issue with where the border should be. But probably the former. So the relevant change will likely be to the CRTC, a distinct component. Or I'll just recentre the window crop. Either way, I need to check it out more closely and it shouldn't affect what's already gone in.

The composite mode is a full, genuine composite encode and decode so it should be accurate. Not overblown or just a bunch of subjective things I think look like a TV or anything like that. But subject to my proper comprehension of composite video, of course.

**Comment by TomHarte** [comment]
After reviewing http://www.cpcwiki.eu/index.php/CRTC I decided that was just poor framing. The CRTC is set up for 40 columns of output in a full line of 64, with HSYNC starting in column 46 and running for 14 columns. So I make that sync starting 6 columns after pixels have ended and running until 60, leaving 4 columns without pixels on the left. Which is what it's showing given that the article also states that "The border has ... lower priority than the black colour output when HSYNC/VSYNC are active".

So I've just changed the visible area.

Still no fix for the leftover noise on the right.

**Comment by reidrac** [comment]
The border is now a bit smaller on the left. I don't know if that's how it looks when I use my TV instead of the Amstrad monitor.

**Comment by TomHarte** [comment]
I've posted http://www.cpcwiki.eu/forum/programming/crtc-comprehension-are-the-basic-display-modes-lopsided/ to confirm or deny my understanding of this; in a sense it'd be a good thing if I were wrong because it would mean that one of the deficiencies in my implementation had been uncovered.
