### ISSUE TITLE
Artifacts in in MSX fullscreen svideo

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#524]
Looks similar to what we had on the CPC, but in MSX with display=svideo.

![photo6030473734348975458](https://user-images.githubusercontent.com/120189/44195806-122a5100-a132-11e8-98fc-d649f69f2d83.jpg)

This is SDL (Linux).

**Comment by TomHarte** [comment]
I think that might be a transition error; the output is normally generated at window size but when you scale the window it attempts to remap what it already has. That could easily go out of bounds if rounding were slightly different.

I might think on this a bit before acting though; it's starting to feel like the overall system I'm using might just be a little too fragile to these sorts of issues.

Very early versions of the emulator didn't use an accumulating framebuffer, they redrew all historic scans that might contribute to a frame for every frame. Which was a lot slower but avoided this sort of problem. There's probably a smarter middle ground to be found.

**Comment by reidrac** [comment]
I'm sorry to say this is back; using master, I can see one blue line at each side of the screen.

**Comment by TomHarte** [comment]
Believed fixed by #581
