### ISSUE TITLE
Monochrome mode

### ISSUE THREAD

**Issue by sup4rl33thax0r** [TomHarte/CLK#537]
Would be nice to have a monochrome display mode for mono DHGR graphics!

On the plus side, aside from the color display, it runs my DHGR routine almost perfectly!  The pixel aspect ratio seems to be off, so things are narrower than they should be.

See my work in progress at: [https://github.com/sup4rl33thax0r/keplermatik-map](https://github.com/sup4rl33thax0r/keplermatik-map).  You can find a disk image in the build directory, keplermatik.dsk.  Working now on cleaning up code and commenting everything.  It is similar to, but not exactly like VBMP.  I actually had a running implementation before finding VBMP but it was slower, added some optimizations I found in that project and now it runs at the same speed.  Just BRUN KEPLERMATIK after booting the image to see the result.  You can put any mono 560x192 bitmap on the image as IMAGE.BMP (type $F2) to see it work but the default is a map from the below project.

This is part of a larger project:  [https://hackaday.io/project/5358-keplermatik](https://hackaday.io/project/5358-keplermatik).  I'm using Cold War-era hardware to build a mission-control style console for tracking amateur radio satellites.

**Comment by TomHarte** [comment]
Monochrome mode added by #581 ; will appear in the next release.

<img width="712" alt="screenshot 2019-02-27 at 18 56 30" src="https://user-images.githubusercontent.com/1162152/53531561-748ce280-3ac1-11e9-8522-913fd3fc595a.png">

**Comment by sup4rl33thax0r** [comment]
Wow thanks!

**Comment by TomHarte** [comment]
I'm still working on the next release, so this is very, very provisional — especially with regard to some additional optimisations I want to make — but a newly-built version is attached should it be helpful in the interim.
[Clock Signal 2019-02-27.zip](https://github.com/TomHarte/CLK/files/2913239/Clock.Signal.2019-02-27.zip)
