### ISSUE TITLE
Distorted screenshots

### ISSUE THREAD

**Issue by Shrapnel21** [TomHarte/CLK#584]
Hi everyone! =)
I'm using the latest version on macOS and, while taking screenshots in The Dawn of Kernel for CPC, I found out they're heavily distorted. This never happened to me before, although the last screenshots I took were admittedly saved in a previous version of CLK.
Am I doing something wrong? =P

![clock signal screen shot 04-01-2019 14 09 46 cet](https://user-images.githubusercontent.com/15562959/50689824-755a4880-102b-11e9-9372-6f4090afb71d.png)

![clock signal screen shot 04-01-2019 14 10 28 cet](https://user-images.githubusercontent.com/15562959/50689827-755a4880-102b-11e9-8e35-733e202d53d2.png)

**Comment by Shrapnel21** [comment]
Tried with another game (Operation Alexandra), same result. =P

![clock signal screen shot 04-01-2019 17 10 50 cet](https://user-images.githubusercontent.com/15562959/50697902-de4dba80-1043-11e9-8a0c-6f163daaf077.png)
![clock signal screen shot 04-01-2019 17 11 34 cet](https://user-images.githubusercontent.com/15562959/50697903-de4dba80-1043-11e9-958d-5c1619b77c78.png)

**Comment by TomHarte** [comment]
This is definitely a bug; I strongly suspect I'm failing to announce or to respect an alignment requirement. On the plus side, if that's true then you might be able to get lucky by trying different window sizes in the meantime. But will fix.

On the plus side, it's completely orthogonal to the ongoing trek through the video subsystem. So it shouldn't be a hard fix.

**Comment by Shrapnel21** [comment]
Great, thanks! =)

**Comment by Shrapnel21** [comment]
And you were right, of course: this was taken after enlarging the window a little. =)

![clock signal screen shot 04-01-2019 18 07 55 cet](https://user-images.githubusercontent.com/15562959/50700811-ced26f80-104b-11e9-994b-dad84dcd2fd8.png)
