### ISSUE TITLE
Fullscreen (ALT + ENTER) not working in Linux

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#751]
I updated to 2020-02-12 and full screen (ALT + ENTER) has stopped working.

**Comment by TomHarte** [comment]
Should be resolved by #756 just landed; I'd slightly rearranged the relevant code for scope, to benefit a mutex ownership issue, but stupidly moved the alt+enter checker, which tests on key-up, into a section that is entered only upon a key-down.

**Comment by reidrac** [comment]
Yes, it is fixed. Thanks!
