### ISSUE TITLE
Key remapping?

### ISSUE THREAD

**Issue by SmallRoomLabs** [TomHarte/CLK#762]
I was thinking "wouldn't it be cool to write a basic game as it was 1985 again?", so I fired up CLK and discovered that all non a-z,0-9 keys on my keyboard mapped to something completely else in the emulated machine. Having to hunt around for the + or = sign takes all the fun out of the experience. ;-(  Of course I can plug in separate keyboards with sticky labels on the keytops, but it feels a bit extreme.

Would it be possible to have a switchable, per target, keyboard mode setting, where in the normal mode it is just as it is now, but in "programming" mode the keys are mapped as close as possible with the actual legend on the physical keyboard?

So if I press shift-0 on my macbook I'll get a right parenthesis in all emulated machines.

The "programming" mode would be awful for gaming and actually running software on the machines, but it would make life so much easier when you want to type in text.

**Comment by TomHarte** [comment]
I can certainly give it a shot. Many of the machines can already map meaningful text to the machine's native format in order to support text pasting and because often it's necessary to start up the machine, so probably I could extend that. I might need to improve it in a few places though. I'll try to give it a look sometime soon.

Is there any particular machine you'd be most interested in?

**Comment by TomHarte** [comment]
I don't know which build you're using, but attached is a preliminary attempt at this feature for macOS, and you can see the branch 'LogicalKeyboards' if you're a Linux user (or, if that branch is gone, I've probably merged it). On macOS check out the new option in the 'Input' pull-down menu. For the SDL build there's a new command-line option.

I'm going to test it a while longer before merging it, and offhand I think it may not work with the Macintosh or the Atari ST, but everything 8 bit should work.
[Clock Signal logical keyboard test #1.zip](https://github.com/TomHarte/CLK/files/4271337/Clock.Signal.logical.keyboard.test.1.zip)

**Comment by SmallRoomLabs** [comment]
It seems to be quite well.  I took the CPC for a quick spin on macOS and it worked just as I wanted. On the VIC20 both Delete and Enter stopped working while in the new "symbol mode" though.

I'll do some more testing (and keep notes about any niggles I encounter) the new couple of days while trying to re-familiarizing myself to basic and the particular dialect to be able to write something game-like.

**Comment by TomHarte** [comment]
There might still be a few rough edges here and there, but I think this is mostly resolved now. Certainly enough to deal with remaining issues as bugs. So I merged the code, which closed this ticket, but please don't hesitate to post back here if any other big issues jump out.

A new build is attached; I want to get at least one more thing done before I go for a full 'release'.
[Clock Signal logical keyboard test #2.zip](https://github.com/TomHarte/CLK/files/4273452/Clock.Signal.logical.keyboard.test.2.zip)
