### ISSUE TITLE
[Amstrad CPC] Keyboard misbehaving in 2020-03-07

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#767]
The keyboard doesn't seem to work properly. Some key combinations with the cursor don't seem to work and sometimes the input gets "stuck" with the key pressed.

This is running on Linux.

**Comment by TomHarte** [comment]
I'm already thinking I may have been too ambitious here; the intention was that, even without the new `--logical-keyboard`, if you press a key on your keyboard that doesn't map to anything on the target machine then an attempt is made to type whatever is printed on your keyboard. But the mechanics of that on SDL probably should have dissuaded me, as you're left to correlate keypresses and typed characters for yourself. So I should abandon that, for that target.

If there are any particular combination of keypresses you'd like me to test, shout out.

(for the record, --logical-keyboard tries to do the opposite thing, of doing regular key actions for anything that doesn't produce a symbol, like cursor keys. So I'll still need to try to combine the two streams of information, but it needn't affect normal use)

**Comment by reidrac** [comment]
I didn't run many tests TBH. The cursor doesn't work, either some combination fail or some keys get stuck, so I reverted to the previous release.

Let me know if you want to me to test anything, happy to help!

**Comment by TomHarte** [comment]
Oh, that's even worse than I feared. I didn't see those issues, but I am relying on a couple of things being true that won't necessarily be — that SDL will provide sensible timestamps for both kepresses and text entry, and that those timestamps will approximately correlate.

I'll look at this tonight. It's just as serious as a crash in my opinion in that it prevents meaningful use of the emulator.

**Comment by reidrac** [comment]
Thanks Tom. I'm fine with the previous release.

**Comment by TomHarte** [comment]
Okay, so I'm optimistic that #769 just merged should return the old behaviour when using a regular physically-mapped keyboard; it should also do a better job with a logically-mapped one as I spotted a glaring omission in my work. But I still need to work on that more, I think.

So if you are willing then please give the updated master a try. Otherwise I'll test some more and then update the release if and when I'm happier.

**Comment by reidrac** [comment]
Code in master seems to be OK!
