### ISSUE TITLE
0/0

### ISSUE THREAD

**Issue by Gusaroo** [TomHarte/CLK#813]
I’m emulating ZX81 games and for some reason none of them work and they load to a 0/0 screen

I’m no expert on the ZX81 so maybe this is normal but any help would be great

**Comment by TomHarte** [comment]
Ugh; I filed this a long time ago as #346 but then came to believe that it didn't affect most software based on random sampling. Clearly I was overconfident.

0/0 is the ZX81's way of telling you that it has finished loading. The emulator needs to trap this automatically but doesn't yet; you can run the software that just loaded by pressing 'r', which should cause 'RUN' to appear on screen, and then pressing enter.

I'm going to look at that ticket again.

**Comment by Gusaroo** [comment]
Thanks my games finally load

**Comment by TomHarte** [comment]
Cool. And I think I've hit upon the proper formula for having the emulator do this automatically, so I'll be merging that soon for the next release.
