### ISSUE TITLE
Floating point exception running Abbaye Des Morts on MSX

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#826]
MSX ROM. This is master on Linux (SDL); you can grab the ROM from:

https://github.com/retrodeluxe/AbbayeMSX

**Comment by TomHarte** [comment]
The linked pull request fixed the crash, which was to do with the way that speed tweaking matching maps onto machines undergoing dynamic analysis. The emulator will tweak speeds if it is trying to get emulated and host vertical sync into phase, to reduce tearing; it uses dynamic analysis to determine the correct paging hardware for large MSX cartridges.

That said, for some reason all of these large cartridges seem to be mute. So I'm going to keep this ticket open until that's fixed. But certainly pull master in the meantime to eliminate the crash.
