### ISSUE TITLE
68000 refactoring

### ISSUE THREAD

**Issue by TomHarte** [TomHarte/CLK#827]
Objective: permit a move into non-cycle-accurate emulation for 68040-class machines, such as Quadras and NextSteps.

So:

1. factor out existing disassembler step to map from instruction code to semantic meaning — operation plus addressing modes plus relevant registers and constants;
2. consider reformulating the 68000 around microinstructions by operation + addressing modes, which would likely be a much smaller table and would mostly avoid the existing after-the-fact duplication detection;
3. make disassembler optionally able to decode instruction sets for later members of the family;
4. implement a non-bus-minded executor based on that — something more like a '90s emulator, or like CP/M for OS X, where the executor has direct ownership of RAM and accesses without much of a mind towards signalling or timing.

It might also be appropriate to create a FrameSource analogue to the ScanTarget for non-accurate machines? So: pull a complete frame atomically, synthesised only upon request.

It's definitely worth looking for lessons here before checking in on ARM and x86 emulation.

**Comment by qeeg** [comment]
I mean, some x86 machines will need cycle-accurate emulation as well, mostly just to handle demos for the IBM XT and stuff such as 8088MPH.

**Comment by TomHarte** [comment]
Agreed entirely; to the extent that there is currently a plan at all, I'm imagining that the best way to handle these sort of machines is to try to be cycle accurate to the early members and then to offer a generic 'fast' version.

So for the Macintosh it'd probably be cycle-accurate Macintoshes as currently implemented plus an arbitrarily fast Quadra; for PCs I'd try for a cycle-accurate 5150 and 5160 but then just offer e.g. 'generic 386', and similarly for the Archimedes probably at least one accurate 26-bit ARM and then generic/fast implementations of the 32-bit ARMs.

This fits my definition of accuracy — all of those platforms stop being defined at the bus-cycle level as they mature. You cross a line somewhere where emulating at that level is no longer adding anything in terms of accuracy, it's just subtracting from speed and clarity.

This is all somewhat future thought though; I've the Metal/Apple Silicon and Windows ports to get through before I can get back to expanding the machine repertoire.

**Comment by TomHarte** [comment]
Noting that I've started throwing thoughts together for CLK's expansion into '90s-era computers at [Roadmap for Flexibly-Timed Platforms](https://github.com/TomHarte/CLK/wiki/Roadmap-for-Flexibly-Timed-Platforms).
