### ISSUE TITLE
Test, release on Apple Silicon

### ISSUE THREAD

**Issue by TomHarte** [TomHarte/CLK#851]
There should be no impediment to the emulator just working — on the Mac it's a Cocoa app which uses Metal for output and the M1 appears not to have any additional requirements for alignment that I might unwittingly have tripped over. I guess the main potential obstacles are a latent error in concurrency or some accidental assumption about timer precision somewhere.

That said: the 16gb Macs are currently not shipping until almost 2021. So this will be on the back burner at least until then.

**Comment by TomHarte** [comment]
That being said, here's [an M1 build that might or might not work](https://github.com/TomHarte/CLK/files/5570215/Clock.Signal.M1.test.build.zip).

No support is offered, etc. I have absolutely no idea.

**Comment by Tiza59** [comment]
I'm actually running the X86-Version on a M1 Powerbook and it works seamlessly. I will test your M1 build tomorrow.

**Comment by TomHarte** [comment]
Thanks! Having waited for reviews from outlets I trust I'm pretty far back in the hardware queue — I'm not expecting to have access to an M1 until after Christmas. I was optimistic the Intel build would be fine, as it's mostly serviceable even on my Core M Retina MacBook, but wasn't even sure of that.

So, fingers crossed!

**Comment by Tiza59** [comment]
Congratulations. Your first universal build runs fine on M1. Also the Mac Plus-ROM-Image installed previously was used by the emulator without asking to drop it again.

**Comment by TomHarte** [comment]
Fantastic, thanks! In that case I've bumped it up to an official release.

I'm sure Rosetta was doing a great job, and the reviews impart that neither actively-cooled machine has much of a throttling problem and that both laptops already have excellent battery life, but I'm sure nobody would turn down even better behaviour.
