### ISSUE TITLE
Apple II disks not loading with ROM P6 with checksum b72a2c70

### ISSUE THREAD

**Issue by ivanizag** [TomHarte/CLK#860]
I was not able to boot an Apple IIe machine with a disk with DSK dos format. It ended up being a problem with the Disk II P6 ROM I was using.

For the Disk II 16-sector state machine ROM, there are two accepted checksums (0x9796a238, 0xb72a2c70). Using 0x9796a238, I manage to boot with a disk, but not with 0xb72a2c70.

As fas as I understand, on DiskII::set_state_machine(), there is code to transform the ROM 0x9796a238 to what the rest of the program expects, and everything works fine. But the ROM 0xb72a2c70 is used as is. it looks like the value of the bytes is right but the order is not what is needed. state_machine_ ends up being different for the two ROMS.

There may also be a problem copying only 128 bytes in
`		memcpy(&state_machine_[0], &state_machine[0], 128);`
but changing that to 256 is not enough to fix that ROM.

**Comment by TomHarte** [comment]
When I'm back from a holiday I'm currently one I'll see which I usually test with; the code's intent is indeed to be able to deal with either of the common dumps on the internet — but it's possible I've failed to allow for the fact that shuffling bit order within bytes also changes lookup order.

**Comment by ivanizag** [comment]
Have a nice holiday! And thanks for all this interesting code to read and learn.

**Comment by TomHarte** [comment]
So I think the merged pull request as above should have fixed this issue, and I'll trigger a new Snap build shortly.

I had indeed not allowed for the ROM that is already in Beneath ProDOS byte order still having slightly different addressing from the internal scheme.

**Comment by ivanizag** [comment]
I can confirm that it works now with both ROMs I was using. Thanks.
