### ISSUE TITLE
ADFS Files

### ISSUE THREAD

**Issue by daveejhitchins** [TomHarte/CLK#864]
Clock Signal recognises .adf files but not .adl files (!) - giving a "The document “xxxxx.adl” could not be opened. " error.
Running on Mac OS Big Sur 11.1

**Comment by TomHarte** [comment]
Based on a quick look at the source code, it appears I've forgotten about ADLs entirely — my ADF class assumes single-sided geometry. Should be an easy fix. I'll look at it as soon as I [finally] get off the IIgs branch.

**Comment by TomHarte** [comment]
Try the attached binary; it supports ADL files and includes an elementary detection mechanism to include the AP6 paged ROM, along with the assumption that if it's doing that then providing sideways RAM would also be sensible.
[Clock Signal.zip](https://github.com/TomHarte/CLK/files/5899203/Clock.Signal.zip)

**Comment by daveejhitchins** [comment]
Hi, Tom . . . 

Everything now works in terms of ADFS and the Plus 1 support - brilliant! I’ve been able to play all of the ADFS game 'discs' I’ve put together.

I have noticed an anomaly - when you 'move' any of the 'windows' it leaves the old one there e.g. 



Just a question: Would it be an enormous job to add a hard drive? (Tut! Are we never satisfied?  😇 )

Thanks and best regards - Dave H.

**Comment by TomHarte** [comment]
I don't know that I've ever had possession of a hard drive image for the Electron; any idea what file format, ROM and controller chip combination is most common?

**Comment by daveejhitchins** [comment]
Hi, Tom . . . 

> I don't know that I've ever had possession of a hard drive image for the Electron; any idea what file format, ROM and controller chip combination is most common?
> 

It’s always a SCSI drive run from the embedded code in ADFS. BeebSCSI is a hardware example and I’ve attached an image of one from BeebEm. These images can be dropped into Jon Welch’s ADFS Explorer. The hardware is attached to the 1MHz Bus.

BRs - Dave H.

**Comment by TomHarte** [comment]
The hard disk image attachment didn't seem to make it to GitHub but, regardless: I've already enough of an implementation of a SCSI drive to satisfy the Macintosh Plus, so it could be a good thing to add an additional controller and host platform, the better to kick the tyres on that.

... especially if my understanding of https://www.domesday86.com/?page_id=64 is correct, and the Acorn SCSI host adaptor is pretty much just wiring the SCSI bus to the 6502 bus and letting the processor deal with it. I was expecting some sort of formal controller chip, but it seems possibly there is none.

**Comment by TomHarte** [comment]
Try the attached if you get a chance — hard disk support is 90% working; the main remaining mystery is why the end of each `SAVE` is met by a `Disc error 7F at :0/000000` given that the save is successful, with whatever you save subsequently being visible in the catalogue and persisting in the disk image between emulator launches.

I guess my SCSI implementation has some sort of latent deficiency, but I don't know what it is yet. There's no error code &7F listed in the ADFS User Guide, which starts at &92. So no clues there.
[Clock Signal.zip](https://github.com/TomHarte/CLK/files/5901617/Clock.Signal.zip)

**Comment by daveejhitchins** [comment]
Hi, Tom . . . 

Fantastic progress . . . . 

I’ve been playing with the latest code you sent - I can confirm the 7F error. At the same time ADFS dumps you back into the root directory, regardless of how deep you are into a tree e.g. If you are 3 levels deep and create a new directory you end up back in $.

I’ve noticed: with ADFS the ^ key is used to drop back into the previous directory, however, I can’t find the character without using the real keyboard layout (command L). The copy key is also missing - I usually remap this one to the \ key (on the real keyboard)

I wonder if JGH could shed some light onto the 7F error?

BRs - Dave H.
> Try the attached if you get a chance — hard disk support is 90% working; the main remaining mystery is why the end of each SAVE is met by a Disc error 7F at :0/000000 given that the save is successful, with whatever you save subsequently being visible in the catalogue and persisting in the disk image between emulator launches.
> 
> I guess my SCSI implementation has some sort of latent deficiency, but I don't know what it is yet. There's no error code &7F listed in the ADFS User Guide, which starts at &92. So no clues there.

**Comment by TomHarte** [comment]
I think I've fixed the saving issue; it was failure properly to gate when Acorn's SCSI interface loads data onto the bus, corrupting the perceived status byte. Which naturally affected writes only, and that things worked again after a remount was just the luck that Acorn writes a 0 back into that latch. Check out the new binary attached and tell me what you see.

I get ^ with shift+left, which is where it's supposed to be, isn't it?

I currently have only backtick mapped to copy; I've added backslash to the default set since that's not mapped to anything, and it's even in the right place on a US keyboard.

[Clock Signal.zip](https://github.com/TomHarte/CLK/files/5915512/Clock.Signal.zip)

**Comment by daveejhitchins** [comment]
Hi, Tom . . . 

Just had a quick 'play' and everything seems to be working 😃
> I think I've fixed the saving issue; it was failure properly to gate when Acorn's SCSI interface loads data onto the bus, corrupting the perceived status byte. Which naturally affected writes only, and that things worked again after a remount was just the luck that Acorn writes a 0 back into that latch. Check out the new binary attached and tell me what you see.
> 
> I get ^ with shift+left, which is where it's supposed to be, isn't it?
> 
D’oh! it’s just where you say it is - I’m so used to looking for the keys in their physical place - didn’t even think of shift-left!

> I currently have only backtick mapped to copy; I've added backslash to the default set since that's not mapped to anything, and it's even in the right place on a US keyboard.
> 
And the 'copy' key works too (not sure what backtick is <blush>).

Over the next week I’ll get my development SCSI Drive installed plus my working ROM set (ABE and ADT) and give the combination some thrashing. It’ll be good to restart my MGC MKII project - although it will probably take a while to remember just where I had left off just before the first lock-down . . . Although I found, a long time ago, that REMing every line does pay off!!!

Many thanks and best regards - Dave H

p.s. I’ll keep you up-to-date on any things I encounter.

**Comment by TomHarte** [comment]
Cool. But, yeah, I think I've been in America too long: on the Apple keyboards here back tick sits proudly in the top left above tab and below escape, where § still inexplicably sits on a British Apple keyboard. So it's fairly prominent. But backslash is a better choice since it's over near where copy should be on both British and American keyboards...

Anyway, I'll shut the ticket for now, definitely report back with any further issues.
