### ISSUE TITLE
Atari ST no longer booting

### ISSUE THREAD

**Issue by mikoenig** [TomHarte/CLK#922]
First of all, thanks for putting so much effort into this interesting project of yours!

I've noticed that the emulated Atari ST is no longer booting (it seems to hang with a white screen).
The last release that still boots is 2021-03-25, so the problematic change must have happened somewhere between then and 2021-04-06.

BTW, from the code it looks like you are theoretically emulating the Atari ST high resolution (i.e. monochrome), but I don't see a way to enable it. Have I missed something?
Unfortunately, one of my most nostalgic games (Ballerburg) only works in high resolution.

**Comment by TomHarte** [comment]
I'll check it out; obviously the ST has that very long delay if you launch it without a disk inserted, so I think that's probably hidden the issue from my somewhat superficial manual testing. I really need to do a better job on testing, to be honest.

High-resolution mode is sufficiently buggy that I decided to leave it unexposed until I get a chance to give the video implementation a serious second going-over. With regard to the implementation, I think I've crossed a threshold where my attempt to handle sequence points ad hoc has become unmanageable.

Anyway, I'll make sure I at least correct whatever mistake I've recently introduced in the short term.
