### ISSUE TITLE
Unified settings

### ISSUE THREAD

**Issue by michellekg** [TomHarte/CLK#964]
How about unified settings windows instead of bunch of little windows? Or even better - standard macOS settings window activated by Cmd+,?

If that's too much for now - please, can you remove all this window by default in fullscreen mode? It's kinda tiresome close them manually every time.

**Comment by TomHarte** [comment]
They're per-window so `command+,` isn't appropriate, but you're completely right that `NSPanel`s are no longer commonly used. As an example of Mac-specific software, Pixelmator Classic (first released 2007) uses a lot of panels; Pixelmator Pro (a decade younger, introduced 2017) keeps everything in a single window.

It's also weird that I don't seem to be able to make my mind up on this stuff. Some per-machine options are in the panel, some are in the menu bar, and volume acts like a media overlay. It definitely wouldn't kill me to pare down from three ways of offering options to at most two.

I guess I'm most tempted to throw them into a bigger version of the overlay that currently contains the volume slider, as I had plans at some point to add at least a play/pause button in there, and possibly rewind if I ever get my state snapshot support up to snuff.

But, yes, I should do _something_.

**Comment by TomHarte** [comment]
Marked as high priority. The more I think about it, the more that having an out-of-step UI bothers me.

**Comment by michellekg** [comment]
> Marked as high priority. The more I think about it, the more that having an out-of-step UI bothers me.

Very nice! But why Cmd+, isn't appropriate?

**Comment by TomHarte** [comment]
> Very nice! But why Cmd+, isn't appropriate?

Cmd+, sets application-wide settings. The settings you're referring to are individual to a machine, they are not application-wide.

Suppose you have three windows open: two Acorn Electrons and one Macintosh Plus. You hit command+comma. Which options does it show — those for the Electron or those for the Macintosh Plus? If it shows the Electron and you change the display type, which Electron does that apply to? And what about machines like the ZX81 that have tape play/pause in their options? Should all ZX81s have a single tape play/pause button?

**Comment by michellekg** [comment]
It's true, you have individual settings for each computer, but you can also have global settings like "Folder for screenshots", "Screenshot format" etc.

"Pixel perfect mode" also can be global setting, althought it's debatable.

But you're totally right - you should have individual and visible setting for each window.
